---
title: "Automatización de corecion de entregas Datacamp"
author: "Mario Juan Moya"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    echo: true
    number_sections: true
    theme: spacelab
    toc: true
    figure_caption: "Figura"
    table_caption: "Tabla"
  html_document:
    echo: true
    number_sections: true
    theme: lumen
    toc: true
  html_notebook:
    echo: true
    number_sections: true
    toc: true
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
  bookdown::pdf_document2:
    toc: true
    toc_depth: 3
    number_sections: true
    figure_caption: "Figura" # Referencias en castellano
    table_caption: "Tabla"
always_allow_html: true
params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
subtitle: "Tratamiento de los Datos. Grado en Ciencia de Datos- UV"
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# CONFIGURACIÓN GENERAL
library(dplyr)      
library(stringr)  
library(readxl)     
library(openxlsx)   
library(knitr)

options(width = 100)

# Opciones generales de los chucks. Se utilizarán salvo cambios en el chunk
opts_chunk$set(echo=F, message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 200, tidy = F, cache.path = '.cache/', fig.path = './figura/')

# Opciones generales de dígitos cuando se incluyen tablas
#options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
#knit_hooks$set(plot = knitr:::hook_plot_html)
```


```{r}
#Expresión regular para buscar todos los ficheros de puntuaciones en la carpeta descomprimida 
rutas_puntos <- list.files("entregas", 
                           pattern = "puntos.*\\.txt$", 
                           recursive = TRUE, 
                           full.names = TRUE, 
                           ignore.case = TRUE)
rutas_puntos

#Expresión regular para buscar todos los ficheros con el justificante del curso
rutas_justificantes <- list.files("entregas", 
                                  pattern = "certificate.*\\.(pdf|png|jpg|jpeg)$", 
                                  recursive = TRUE, 
                                  full.names = TRUE, 
                                  ignore.case = TRUE)
rutas_justificantes


#¿Todas las entregas contienen el fichero de puntos y el justificante de realización del curso ?

cat("Análisis de archivos presentes:\n")
cat("- Entregas con puntos:", length(rutas_puntos), "\n")
cat("- Entregas con certificado:", length(rutas_justificantes), "\n")




#Creación de las variables del dataframe  
apellidos <- c()
contenido <- c()
puntos_num <- c()
nombre_fichero <- c()

for (i in seq_along(rutas_puntos)) {
  
  ruta <- rutas_puntos[i]
  partes_ruta <- str_split(ruta, "/")[[1]]
  carpeta_alumno <- partes_ruta[2] 
  
  apellidos_nombre <- str_split(carpeta_alumno, "_")[[1]][1]
  apellidos[i] <- str_split(apellidos_nombre, ",")[[1]][1]
  
  contenido[i] <- readLines(ruta, warn = FALSE)[1]
  
  # Extraigo solo los dígitos del texto usando str_extract de stringr
  # "\\d+" significa "uno o más números"
  puntos_num[i] <- as.numeric(str_extract(contenido, "\\d+"))
  
  # Extraigo el nombre exacto del fichero
  nombre_fichero[i] <- basename(ruta)
  
  
}

#¿Todas las entregas usaron como nombre del fichero de puntos el indicado; puntos.txt ?¿Cuántas variantes hay ?

table(nombre_fichero)


#Creación dataframe
evalua_df <- data.frame(
    apellidos = apellidos,
    puntos = puntos_num,
    NomFile = nombre_fichero,
    Puntos = contenido,
    stringsAsFactors = FALSE
  ) %>% arrange(apellidos)


# Guardo primer Excel
write.xlsx(evalua_df, "NotasRIntermedio.xlsx")


#Cargo Excel de alumnos matriculados
alumnos_matriculados <- read_excel("AlumnosTD25_26.xlsx")

#Combino dataframes
AlumnosNotas <- alumnos_matriculados %>%
  left_join(evalua_df, by = "Apellido(s)") 
```







